version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smarthome
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/smarthome"
    volumes:
      - //./pipe/docker_engine://./pipe/docker_engine  # Docker Named Pipe einbinden

  server:
    build: ./server
    depends_on:
      - backend
    ports:
      - "3001:3000"

  thermostat_sensor:
    build: ./thermostat_sensor
    depends_on:
      - backend
    ports:
      - "5000:5000"
    environment:
      - SENSOR_INTERVAL=5000
    volumes:
      - ./thermostat_sensor:/usr/src/thermostat_sensor

  window_sensor:
    build: ./window_sensor
    depends_on:
      - backend
    ports:
      - "4001:4000"
    environment:
      - SENSOR_INTERVAL=5000
    volumes:
      - .:/usr/src/window_sensor

volumes:
  postgres_data: