version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - window_sensor

  window_sensor:
    build: .
    ports:
      - "4001:4000"

    environment:
      - SENSOR_INTERVAL=5000
    volumes:
      - .:/usr/src/window_sensor
      - /usr/src/window_sensor/node_modules

  thermostat_sensor:
    build: ./thermostat_sensor
    ports:
      - "5000:5000"
    environment:
      - SENSOR_INTERVAL=5000
    volumes:
      - ./thermostat_sensor:/usr/src/thermostat_sensor
