version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smarthome
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/smarthome"
    volumes:
      - //./pipe/docker_engine://./pipe/docker_engine  # Docker Named Pipe einbinden
      - /var/run/docker.sock:/var/run/docker.sock

  server:
    build: ./server
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app/client  # Client-Code ins Server-Container mounten

  thermostat_sensor:
    build: ./thermostat_sensor
    depends_on:
      - backend
    ports:
      - "5000:5000"
    environment:
      - SENSOR_INTERVAL=5000
      - CONTAINER_NAME=thermostat_sensor_name  # Platzhalter für den Namen, wird dynamisch gesetzt

  window_sensor:
    build: ./window_sensor
    depends_on:
      - backend
    ports:
      - "4001:4000"
    environment:
      - SENSOR_INTERVAL=5000
      - CONTAINER_NAME=window_sensor_name  # Platzhalter für den Namen, wird dynamisch gesetzt

volumes:
  postgres_data:  # Definition des Volumes für PostgreSQL-Daten