# Verwende das Node.js-Image als Basis
FROM node:18

# Arbeitsverzeichnis erstellen
WORKDIR /usr/src/app

# Kopiere package.json und package-lock.json
COPY package*.json ./

# Installiere die Abhängigkeiten
RUN npm install

# Kopiere den Rest des Anwendungscodes
COPY . .

# Exponiere den Port 3001
EXPOSE 3001

# Definiere den Startbefehl
CMD ["npm", "start"]